# Generated by Django 4.0.5 on 2023-01-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unique_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
