# Generated by Django 4.0.5 on 2023-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_article_visuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
