# Generated by Django 4.0.5 on 2023-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default='diodytTx', max_length=8),
        ),
    ]
